### ISSUE TITLE
Credits for Zoe v1

### ISSUE THREAD

**Issue by MrGamingBR** [LMS5413/LM-BOTS#1]
Hi, Your bot, LM RADIO, it's a copy of my bot's old music system. I ask you to give due credit to [Zoe](https://github.com/Zoe-Corporation/Zoe/tree/d7b72a2672fe8301440b4395cf77dd9a8e35b6f7/src/commands/Music).

Good afternoon.

**Comment by LMS5413** [comment]
Oh sorry for not giving you credit! Thanks for your help too.

**Comment by MrGamingBR** [comment]
I'm closing Issue Request now
